[evolution]
initial_population_count = 128
tournament_size = 4
mutation_rate = 0.05
elite_factor = 0.1
persist_top_chromosome = false

[smart_network]
input_count = 149
output_count = 2
nand_count_bits = 10
mem_addr_bits = 8
mem_rw_bits = 8
connection_count = 5000

[game]
visibility_distance = 2
max_steps = 30
levels_dir_path = "levels/"
level_to_times_to_play = { 1 = 100 }
